version: "3.9"

services:
  adb:
    image: adbserver:latest
    command: adb -a nodaemon server
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
      - ./adbkeys/adbkey:/home/adb/.android/adbkey
      - ./adbkeys/adbkey.pub:/home/adb/.android/adbkey.pub
    group_add:
      - ${PLUGDEV_GID}
      - ${ADB_GID}
    device_cgroup_rules:
      - c 188:* rmw
      - c 189:* rmw
